import { readFile } from "node:fs/promises";
import path from "node:path";
import type { NextRequest } from "next/server";

// Serves the large index assets with content negotiation: brotli if the client
// accepts it, else gzip, else the raw file. Next's static serving is gzip-only
// and won't pick a .br sibling, so we do it here from the precompressed files
// generated by `npm run index`.

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const ALLOWED = new Set(["jobs.json", "search-index.json"]);

export async function GET(
  req: NextRequest,
  ctx: { params: Promise<{ file: string }> },
) {
  const { file } = await ctx.params;
  if (!ALLOWED.has(file)) {
    return new Response("Not found", { status: 404 });
  }

  const accept = req.headers.get("accept-encoding") ?? "";
  let encoding = "";
  let ext = "";
  if (/\bbr\b/.test(accept)) {
    encoding = "br";
    ext = ".br";
  } else if (/\bgzip\b/.test(accept)) {
    encoding = "gzip";
    ext = ".gz";
  }

  const body = await readFile(path.join(process.cwd(), "public", file + ext));

  const headers = new Headers({
    "Content-Type": "application/json; charset=utf-8",
    // Fetched with a ?v=<hash> query, so it can be cached forever.
    "Cache-Control": "public, max-age=31536000, immutable",
    Vary: "Accept-Encoding",
  });
  if (encoding) headers.set("Content-Encoding", encoding);

  return new Response(new Uint8Array(body), { headers });
}
