import { readFile } from "node:fs/promises";
import path from "node:path";
import type { NextRequest } from "next/server";

// Serves the baked jobs.json and the prebuilt wasm search index
// (search-index.bin) with content negotiation: brotli if the client accepts it,
// else gzip, else raw — from the precompressed siblings generated by
// `npm run index` (at image-build time, from GCS latest/job_details.json).

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const CONTENT_TYPES: Record<string, string> = {
  "jobs.json": "application/json; charset=utf-8",
  "search-index.bin": "application/octet-stream",
  // The whole descriptions file — only fetched wholesale by the localhost
  // /benchmark page (to index the in-browser JS engine over identical docs).
  // The app itself fetches per-id slices via /dl/desc instead.
  "descriptions.json": "application/json; charset=utf-8",
};

export async function GET(
  req: NextRequest,
  ctx: { params: Promise<{ file: string }> },
) {
  const { file } = await ctx.params;
  const contentType = CONTENT_TYPES[file];
  if (!contentType) {
    return new Response("Not found", { status: 404 });
  }

  const accept = req.headers.get("accept-encoding") ?? "";
  let encoding = "";
  let ext = "";
  if (/\bbr\b/.test(accept)) {
    encoding = "br";
    ext = ".br";
  } else if (/\bgzip\b/.test(accept)) {
    encoding = "gzip";
    ext = ".gz";
  }

  const body = await readFile(path.join(process.cwd(), "public", file + ext));

  const headers = new Headers({
    "Content-Type": contentType,
    // Fetched with a ?v=<hash> query, so it can be cached forever.
    "Cache-Control": "public, max-age=31536000, immutable",
    Vary: "Accept-Encoding",
  });
  if (encoding) headers.set("Content-Encoding", encoding);

  return new Response(new Uint8Array(body), { headers });
}
